name: CI
on:
  push:
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        working-directory: minisqlpp-compiler
        run: mvn -q -DskipTests package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: minisqlpp-compiler-jar
          path: minisqlpp-compiler/target/*-jar-with-dependencies.jar
