name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        working-directory: minisqlpp-compiler
        run: mvn -q -DskipTests package
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: minisqlpp-compiler/target/*-jar-with-dependencies.jar
